### ISSUE TITLE
LDM 6.14.5 printmetrics change with port count reversed?

### ISSUE THREAD

**Issue by akrherz** [Unidata/LDM#120]
I use `ldmadmin printmetrics` to monitor the health of LDM.  With the 6.14.5 release, it appears the upstream/downstream port count is now reversed? it appears this commit 80c80dbe7ef0c45a76ecfbfbd is at play here

On identical LDM nodes. With LDM 6.13.17

```
$ ldmadmin printmetrics
20230222.141553 5.53 6.14 6.05 1 0 112 1533 486482464 27 6 67 0 20766228480 18419310592 0 4294963200 10587
```

on LDM 6.14.5
```
$ ldmadmin printmetrics
20230222.142126 6.39 6.73 6.95 0 1 254 2530 499918912 17 5 78 0 15404175360 16285884416 0 4294963200 16972
```

Note the reversal of the "1 0".  Each LDM node makes a single FEEDME request to a single upstream.

**Comment by semmerson** [comment]
Hi Daryl.

> I use ldmadmin printmetrics to monitor the health of LDM. With the 6.14.5
> release, it appears the upstream/downstream port count is now reversed?
>

That's correct. The reported values were reversed from what they should
have been. LDM 6.14.5 now reports the correct values. I apologize for
taking so long to realize this.

it appears this commit 80c80db
> <https://github.com/Unidata/LDM/commit/80c80dbe7ef0c45a76ecfbfbdfbf44fdaf335e5f>
> is at play here
>
> On identical LDM nodes. With LDM 6.13.17
>
> $ ldmadmin printmetrics
> 20230222.141553 5.53 6.14 6.05 1 0 112 1533 486482464 27 6 67 0 20766228480 18419310592 0 4294963200 10587
>
> on LDM 6.14.5
>
> $ ldmadmin printmetrics
> 20230222.142126 6.39 6.73 6.95 0 1 254 2530 499918912 17 5 78 0 15404175360 16285884416 0 4294963200 16972
>
> Note the reversal of the "1 0". Each LDM node makes a single FEEDME
> request to a single upstream.
>

The latter output is correct. The fifth field is the number of connections
to the local LDM port (388) and the sixth is the number of connections to a
remote LDM port (again 388). A downstream LDM process created as a result
of a REQUEST entry will connect to a remote LDM port.

This error went unnoticed by me and everyone else. I guess people (myself
included) looked at patterns rather than actual values -- when they looked
at the values at all.

I hope this fix isn't too much of an inconvenience and apologize if it is.

Regards,
Steve

**Comment by akrherz** [comment]
No worries, thanks for confirming that the current output is the correct one.
